NumPy is a powerful Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is widely used in data science, machine learning, and scientific computing due to its speed and versatility.

**Key Features:**
- Efficient array operations
- Mathematical and statistical functions
- Linear algebra and random number capabilities
- Integration with other scientific libraries



In [1]:
!pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# create array using numpy
# create a 1D Array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1,2,3,4,5]])

In [5]:
#2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
<class 'numpy.ndarray'>
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Attributes of numpy

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ")
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions:  2
Size (number of elements): 
Data type: int64
Item size (in bytes): 8


In [10]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# element wise addition
print("Addition:",arr1+arr2)

# element wise subtraction
print("Subtraction:" , arr1-arr2)

# element wise multiplication
print("Multiplication: ", arr1 * arr2)

#element wise division
print("Division: ",arr1/arr2)




Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [11]:
#universal function

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))
# log function
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
# array slicing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0][0])


1


In [14]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [15]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [16]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [17]:
#modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [18]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [19]:
#statistical concepts -- Normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev=np.std(data)

normalized_data= (data -mean)/std_dev

print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
mean_normalized_data= np.mean(normalized_data)
std_dev_normalized_data=np.std(normalized_data)
print(mean_normalized_data)
print(std_dev_normalized_data)

0.0
0.9999999999999999


In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:", mean)

#median

median = np.median(data)
print("median: ",median)


#standard deviation
std_dev= np.std(data)
print("Standard deviation: ",std_dev)

#variance
variance = np.var(data)
print("Variance: ",variance)


Mean: 3.0
median:  3.0
Standard deviation:  1.4142135623730951
Variance:  2.0


In [27]:
## logical op

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])