# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [17]:
import numpy as np


array = np.random.randint(1,20,size=(5,5))

print("Original Array:")
print(array)

array[:,2]=1
print(array)


Original Array:
[[ 8  6  3  6  6]
 [ 5  5  9  6 16]
 [ 7 17  5  7  9]
 [ 2 12 13 15  3]
 [ 3  5  8 12 19]]
[[ 8  6  1  6  6]
 [ 5  5  1  6 16]
 [ 7 17  1  7  9]
 [ 2 12  1 15  3]
 [ 3  5  1 12 19]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
array=np.arange(1,17).reshape(4,4)

print(array)

# for i in range(0,4):
#   array[i,i]=0

np.fill_diagonal(array,0)


print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [29]:
array = np.arange(1,37).reshape(6,6)

print(array)

sub_array=array[2:5 , 1:4]

print(sub_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [38]:
array=np.random.randint(1,26,size=(5,5))
print(array)

border_elements=np.concatenate((array[0, :],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print(border_elements)

[[18 12 15 22 11]
 [ 5 18 13 20  7]
 [ 3 24 23 18 10]
 [23  1 18 24  5]
 [14 18 22 17  9]]
[18 12 15 22 11 14 18 22 17  9  5  3 23  7 10  5]


1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [55]:
array1=np.random.randint(1,12,size=(3,4))
array2=np.random.randint(1,12,size=(3,4))

print("array1 :\n",array1)
print("array2:\n",array2)
sum_arr =np.add(array1,array2)
print("Summation of array1 and array2:\n" , sum_arr)
sub_array= np.subtract(array1,array2)
print("Subtraction of array1 and array2:\n",sub_array)
mul_array=np.multiply(array1,array2)
print("Multiplication of array1 and array2:\n",mul_array)
div= np.divide(array1,array2)
print("Division of array1 and array2:\n",div)

array1=np.random.randint(1,12,size=(3,4))
array2=np.random.randint(1,12,size=(3,4))

sum_arr =array1+array2
print("Summation of array1 and array2:\n" , sum_arr)
sub_array= array1-array2
print("Subtraction of array1 and array2:\n",sub_array)
mul_array=array1 *array2
print("Multiplication of array1 and array2:\n",mul_array)
div_array= array1/array2
print("Division of array1 and array2:\n",div_array)




array1 :
 [[ 6  2 10  2]
 [ 1  3  4  3]
 [11  8  4 11]]
array2:
 [[ 6  8  4  8]
 [ 9  5  4 10]
 [ 7 11  2 11]]
Summation of array1 and array2:
 [[12 10 14 10]
 [10  8  8 13]
 [18 19  6 22]]
Subtraction of array1 and array2:
 [[ 0 -6  6 -6]
 [-8 -2  0 -7]
 [ 4 -3  2  0]]
Multiplication of array1 and array2:
 [[ 36  16  40  16]
 [  9  15  16  30]
 [ 77  88   8 121]]
Division of array1 and array2:
 [[1.         0.25       2.5        0.25      ]
 [0.11111111 0.6        1.         0.3       ]
 [1.57142857 0.72727273 2.         1.        ]]
Summation of array1 and array2:
 [[13 10  6  5]
 [ 8 11 20  7]
 [11 15 12 17]]
Subtraction of array1 and array2:
 [[ 3 -6 -2 -1]
 [ 2 -5  0 -1]
 [-3  5  6 -1]]
Multiplication of array1 and array2:
 [[ 40  16   8   6]
 [ 15  24 100  12]
 [ 28  50  27  72]]
Division of array1 and array2:
 [[1.6        0.25       0.5        0.66666667]
 [1.66666667 0.375      1.         0.75      ]
 [0.57142857 2.         3.         0.88888889]]


 Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.